import { Router } from "express";
import {
  obtenerAlquilerFechaInicioController,
  obtenerAlquileresActivosController,
  obtenerAlquileresEntreFechasController,
  obtenerCarrosController,
  obtenerCarrosDisponiblesController,
  obtenerCarrosGrandesController,
  obtenerCarrosGrandesDisponiblesController,
  obtenerClienteDNIController,
  obtenerClienteReservaController,
  obtenerClientesConAlquilerController,
  obtenerClientesController,
  obtenerCostoAlquilerController,
  obtenerDetallesAlquilerController,
  obtenerGerentesController,
  obtenerNumeroAlquileresController,
  obtenerNumeroCarrosController,
  obtenerNumeroCarrosSucursalController,
  obtenerReservasPendientesClienteController,
  obtenerReservasPendientesController,
  obtenerVendedoresController,
} from "../controllers/getControllers.js";
import { limitPets, limitSize } from "../utils/limit.js";
import {
  obtenerClienteDNIDTO,
  obtenerClienteReservaDTO,
  obtenerCostoAlquilerDTO,
  obtenerDetallesAlquilerDTO,
  obtenerReservasPendientesClienteDTO,
} from "./DTO/getDto.js";
import {
  authorizationMiddleware,
  contentMiddlewareAlquiler,
  contentMiddlewareAutomovil,
  contentMiddlewareCliente,
  contentMiddlewareEmpleado,
  contentMiddlewareReserva,
  contentMiddlewareSucursal,
} from "../utils/token.js";

const getInitRoute = () => {
  const router = Router();
  router.get(
    "/obtenerClientes",
    limitPets,
    limitSize,
    authorizationMiddleware,
    contentMiddlewareCliente,
    obtenerClientesController
  );
  router.get(
    "/obtenerCarrosDisponibles",
    limitPets,
    limitSize,
    authorizationMiddleware,
    contentMiddlewareAutomovil,
    obtenerCarrosDisponiblesController
  );
  router.get(
    "/obtenerAlquileresActivos",
    limitPets,
    limitSize,
    authorizationMiddleware,
    contentMiddlewareAlquiler,
    obtenerAlquileresActivosController
  );
  router.get(
    "/obtenerReservasPendientes",
    limitPets,
    limitSize,
    authorizationMiddleware,
    contentMiddlewareReserva,
    obtenerReservasPendientesController
  );
  router.get(
    "/obtenerDetallesAlquiler",
    limitPets,
    limitSize,
    authorizationMiddleware,
    contentMiddlewareAlquiler,
    obtenerDetallesAlquilerDTO,
    obtenerDetallesAlquilerController
  );
  router.get(
    "/obtenerVendedores",
    limitPets,
    limitSize,
    authorizationMiddleware,
    contentMiddlewareEmpleado,
    obtenerVendedoresController
  );
  router.get(
    "/numeroAutosDisponibles",
    limitPets,
    limitSize,
    authorizationMiddleware,
    contentMiddlewareAutomovil,
    obtenerNumeroCarrosController
  );
  router.get(
    "/obtenerCostoAlquiler",
    limitPets,
    limitSize,
    authorizationMiddleware,
    contentMiddlewareAlquiler,
    obtenerCostoAlquilerDTO,
    obtenerCostoAlquilerController
  );
  router.get(
    "/obtenerClienteDNI",
    limitPets,
    limitSize,
    authorizationMiddleware,
    contentMiddlewareCliente,
    obtenerClienteDNIDTO,
    obtenerClienteDNIController
  );
  router.get(
    "/obtenerCarrosGrandes",
    limitPets,
    limitSize,
    authorizationMiddleware,
    contentMiddlewareAutomovil,
    obtenerCarrosGrandesController
  );
  router.get(
    "/obtenerAlquilerFechaInicio",
    limitPets,
    limitSize,
    authorizationMiddleware,
    contentMiddlewareAlquiler,
    obtenerAlquilerFechaInicioController
  );
  router.get(
    "/obtenerReservasPendientesCliente",
    limitPets,
    limitSize,
    authorizationMiddleware,
    contentMiddlewareReserva,
    obtenerReservasPendientesClienteDTO,
    obtenerReservasPendientesClienteController
  );
  router.get(
    "/obtenerGerentes",
    limitPets,
    limitSize,
    authorizationMiddleware,
    contentMiddlewareEmpleado,
    obtenerGerentesController
  );
  router.get(
    "/obtenerClientesConAlquiler",
    limitPets,
    limitSize,
    authorizationMiddleware,
    contentMiddlewareAlquiler,
    obtenerClientesConAlquilerController
  );
  router.get(
    "/obtenerCarros",
    limitPets,
    limitSize,
    authorizationMiddleware,
    contentMiddlewareAutomovil,
    obtenerCarrosController
  );
  router.get(
    "/obtenerNumeroCarrosSucursal",
    limitPets,
    limitSize,
    authorizationMiddleware,
    contentMiddlewareSucursal,
    obtenerNumeroCarrosSucursalController
  );
  router.get(
    "/obtenerNumeroAlquileres",
    limitPets,
    limitSize,
    authorizationMiddleware,
    contentMiddlewareAlquiler,
    obtenerNumeroAlquileresController
  );
  router.get(
    "/obtenerCarrosGrandesDisponibles",
    limitPets,
    limitSize,
    authorizationMiddleware,
    contentMiddlewareAutomovil,
    obtenerCarrosGrandesDisponiblesController
  );
  router.get(
    "/obtenerClienteDeReserva",
    limitPets,
    limitSize,
    authorizationMiddleware,
    contentMiddlewareReserva,
    obtenerClienteReservaDTO,
    obtenerClienteReservaController
  );
  router.get(
    "/obtenerAlquileresEntreFechas",
    limitPets,
    limitSize,
    authorizationMiddleware,
    contentMiddlewareAlquiler,
    obtenerAlquileresEntreFechasController
  );
  return router;
};

export { getInitRoute };
